/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as protectedappRouteRouteImport } from './routes/(protected)/(app)/route'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as protectedappDashboardRouteImport } from './routes/(protected)/(app)/dashboard'
import { Route as protectedSettingsMembersIndexRouteImport } from './routes/(protected)/settings/members/index'
import { Route as protectedappTasksIndexRouteImport } from './routes/(protected)/(app)/tasks/index'
import { Route as protectedSettingsMembersNewRouteImport } from './routes/(protected)/settings/members/new'
import { Route as protectedSettingsMembersMemberIdRouteImport } from './routes/(protected)/settings/members/$memberId'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedappRouteRoute = protectedappRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedSettingsRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedappDashboardRoute = protectedappDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedappRouteRoute,
} as any)
const protectedSettingsMembersIndexRoute =
  protectedSettingsMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedappTasksIndexRoute = protectedappTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => protectedappRouteRoute,
} as any)
const protectedSettingsMembersNewRoute =
  protectedSettingsMembersNewRouteImport.update({
    id: '/members/new',
    path: '/members/new',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsMembersMemberIdRoute =
  protectedSettingsMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof protectedappDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/settings/members/$memberId': typeof protectedSettingsMembersMemberIdRoute
  '/settings/members/new': typeof protectedSettingsMembersNewRoute
  '/tasks/': typeof protectedappTasksIndexRoute
  '/settings/members/': typeof protectedSettingsMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof protectedappDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/settings/members/$memberId': typeof protectedSettingsMembersMemberIdRoute
  '/settings/members/new': typeof protectedSettingsMembersNewRoute
  '/tasks': typeof protectedappTasksIndexRoute
  '/settings/members': typeof protectedSettingsMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(protected)/(app)': typeof protectedappRouteRouteWithChildren
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/(protected)/(app)/dashboard': typeof protectedappDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/(protected)/settings/members/$memberId': typeof protectedSettingsMembersMemberIdRoute
  '/(protected)/settings/members/new': typeof protectedSettingsMembersNewRoute
  '/(protected)/(app)/tasks/': typeof protectedappTasksIndexRoute
  '/(protected)/settings/members/': typeof protectedSettingsMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/$'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/settings/'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/tasks/'
    | '/settings/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/settings'
    | '/settings/members/$memberId'
    | '/settings/members/new'
    | '/tasks'
    | '/settings/members'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(protected)/(app)'
    | '/(protected)/settings'
    | '/api/$'
    | '/(protected)/(app)/dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(protected)/settings/'
    | '/(protected)/settings/members/$memberId'
    | '/(protected)/settings/members/new'
    | '/(protected)/(app)/tasks/'
    | '/(protected)/settings/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(app)': {
      id: '/(protected)/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedappRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/(app)/dashboard': {
      id: '/(protected)/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedappDashboardRouteImport
      parentRoute: typeof protectedappRouteRoute
    }
    '/(protected)/settings/members/': {
      id: '/(protected)/settings/members/'
      path: '/members'
      fullPath: '/settings/members/'
      preLoaderRoute: typeof protectedSettingsMembersIndexRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/(app)/tasks/': {
      id: '/(protected)/(app)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof protectedappTasksIndexRouteImport
      parentRoute: typeof protectedappRouteRoute
    }
    '/(protected)/settings/members/new': {
      id: '/(protected)/settings/members/new'
      path: '/members/new'
      fullPath: '/settings/members/new'
      preLoaderRoute: typeof protectedSettingsMembersNewRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/members/$memberId': {
      id: '/(protected)/settings/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/settings/members/$memberId'
      preLoaderRoute: typeof protectedSettingsMembersMemberIdRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
  }
}

interface protectedappRouteRouteChildren {
  protectedappDashboardRoute: typeof protectedappDashboardRoute
  protectedappTasksIndexRoute: typeof protectedappTasksIndexRoute
}

const protectedappRouteRouteChildren: protectedappRouteRouteChildren = {
  protectedappDashboardRoute: protectedappDashboardRoute,
  protectedappTasksIndexRoute: protectedappTasksIndexRoute,
}

const protectedappRouteRouteWithChildren =
  protectedappRouteRoute._addFileChildren(protectedappRouteRouteChildren)

interface protectedSettingsRouteRouteChildren {
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
  protectedSettingsMembersMemberIdRoute: typeof protectedSettingsMembersMemberIdRoute
  protectedSettingsMembersNewRoute: typeof protectedSettingsMembersNewRoute
  protectedSettingsMembersIndexRoute: typeof protectedSettingsMembersIndexRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsIndexRoute: protectedSettingsIndexRoute,
    protectedSettingsMembersMemberIdRoute:
      protectedSettingsMembersMemberIdRoute,
    protectedSettingsMembersNewRoute: protectedSettingsMembersNewRoute,
    protectedSettingsMembersIndexRoute: protectedSettingsMembersIndexRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedappRouteRoute: typeof protectedappRouteRouteWithChildren
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedappRouteRoute: protectedappRouteRouteWithChildren,
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
